version = 1

test_patterns = ["tests/**"]

[[analyzers]]
name = "sql"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "secrets"

[[transformers]]
name = "black"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "ruff"