version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "secrets"

[[transformers]]
name = "black"
enabled = "true"

[[transformers]]
name = "autopep8"
enabled = "true"

[[transformers]]
name = "ruff"
enabled = "true"


