name: commit-qc-checks

on:
    push:
        branches-ignore:
            - 'main'

jobs:
    python-quality-checks:
        runs-on: ubuntu-latest
        steps:
            - uses : actions/checkout@v4
            - name : 'Python: Setup'
              uses : actions/setup-python@v5
              with:
                python-version: 3.11
            - name : 'Python: Install Dependencies'
              run: |
                python -m pip install --upgrade pip
                pip install flake8 pylint black bandit safety
              continue-on-error: true
            - name : 'Python: Linting'
              run: |
                flake8 .
                find . -name "*.py" | xargs pylint
              continue-on-error: true
            - name : 'Python: Formatting'
              run: |
                black --check .
              continue-on-error: true
    terraform-quality-checks:
        runs-on: ubuntu-latest
        steps:
            - uses : actions/checkout@v4
            - name: 'Terraform: Setup'
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: latest
            - name: 'Terraform: Formatting'
              working-directory: terraform
              run: terraform fmt -check -recursive
              continue-on-error: true
            - name: 'Terraform: Initialise'
              working-directory: terraform
              run: terraform init -backend=false
              continue-on-error: true
            - name: 'Terraform: Validate'
              working-directory: terraform
              run: terraform validate
              continue-on-error: true